name: ðŸ› Bug Report
description: Create a report to help us improve Claude Code JSONL Editor
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true
        - label: I can reproduce this issue consistently
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Start the editor with `jsonl-editor -p ./test.jsonl`
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened instead
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI Interface
        - Server (Express API)
        - Client (Web UI)
        - File Operations
        - Installation/Setup
        - Network/Connectivity
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Claude Code JSONL Editor are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - macOS
        - Windows
        - Linux (Ubuntu)
        - Linux (Debian)
        - Linux (CentOS/RHEL)
        - Linux (Arch)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: "node --version"
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command Used
      description: What exact command did you run?
      placeholder: "jsonl-editor -p ./conversation.jsonl --verbose"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      placeholder: Paste error messages, stack traces, or console output here
      render: text
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - File size or structure details
        - Network environment specifics
        - Any workarounds you've found
    validations:
      required: false

  - type: checkboxes
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information (check all that apply)
      options:
        - label: Using corporate firewall/proxy
        - label: Using custom networking setup
        - label: Running in Docker/container
        - label: Running on remote server
        - label: Using with large files (>100MB)
        - label: Multiple concurrent instances